### ISSUE TITLE
Long questions blend

### ISSUE THREAD

**Issue by s1037989** [KeystoneIT/Ama#49]
![ama](https://cloud.githubusercontent.com/assets/517498/10857796/3320c8fa-7f1e-11e5-9bf8-152e2d627364.JPG)

**Comment by JDorpinghaus** [comment]
This bug appears to be limited to Chrome 47. The bug does not appear in Chrome Canary (currently version 49), perhaps it was fixed?

![browsers](https://cloud.githubusercontent.com/assets/9485088/12081637/c6583bea-b244-11e5-967b-b920c27d692d.png)

**Comment by s1037989** [comment]
Ah!  Great find!  Any workarounds for broken browsers?  Perhaps switch to some sort different styling that isn't effected by a fairly modern browser?

**Comment by JDorpinghaus** [comment]
This bug doesn't occur with my development code (on my Cloud9 account). I must have changed a CSS value a while ago, I don't know for sure what fixed it.

**Comment by s1037989** [comment]
Did you sync your C9 dev code to Github that we shouldn't experience this any more?  I assume you did simply because you've since posted other commits.

EDIT: Pulled your last commits and this is still happening.  It may be an older browser issue, but Chrome 47.0 is fairly newish and fairly common.  Moreover, I think it happens on other browsers, too, but I'm not certain.

**Comment by s1037989** [comment]
Woops, that crap fix only fixed it for the answered questions.  I tried to apply the same table fix to the unanswered section, and it didn't turn out so nice.

**Comment by jsiems** [comment]
Closed by #61
